spring.application.name=Plataforma de compra/venta

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hightlight_sql=true

spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.health.show-details=always

server.port=8080

app.uploads.dir=./uploads

# Mail configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.from=${MAIL_FROM}
app.mail.from-name=${MAIL_FROM_NAME}
app.frontend.url=${APP_FRONTEND_URL}